### ISSUE TITLE
C# internal hack

### ISSUE THREAD

**Issue by lvlkoo** [G-E-N-E-S-I-S/loadlibrayy#1]
Hello! Can I ask you a question? I am new in game hacking, and i am a C# developer... So i see that your injector written in C# and i wanna to ask does it can to inject .net assembly in game? Does hack written in C# can be internal? With easyhook or something like that

**Comment by G-E-N-E-S-I-S** [comment]
yes it can, but it's a hassle and has nothing to do with loadlibrayy
